package package2;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Test203
{
	public static void main(String[] args) throws Exception
	{
		System.setProperty("webdriver.chrome.driver","E:\\SDET\\chromedriver.exe");
        WebDriver driver=new ChromeDriver();
        driver.manage().deleteAllCookies();
        //Count of  Cookies
        int a=driver.manage().getCookies().size();
        System.out.println(a); 
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        //Launch site
        driver.get("http://www.gmail.com");
        //Maximize
        driver.manage().window().maximize();
        //Login
        driver.findElement(By.xpath("//input[@name='identifier']")).sendKeys("suhanthreddy67@gmail.com");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//span[text()='Next']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//input[@name='password']")).sendKeys("Liviya31441");
        Thread.sleep(2000);
        driver.findElement(By.xpath("//span[text()='Next']")).click();
        Thread.sleep(4000);          
        //Input give to select
        @SuppressWarnings("resource")
		Scanner sc=new Scanner(System.in);
        System.out.println("Enter name ex:-Primary");
        String x=sc.nextLine();
        Thread.sleep(5000); 
        WebElement d=driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[7]"));   	
        WebElement e=driver.findElement(By.xpath("//div[@gh='mtb']/div/div/child::div[2]/div[3]"));    	
        WebElement f=driver.findElement(By.xpath("//div[@gh='mtb']/div/div/child::div[4]"));
        Thread.sleep(2000); 
        int i=1;
        {
        	if(x.equals("Trash"))
        	{
        	//Count no.of mails in Trash and Delete 
            Thread.sleep(8000);                       
            driver.findElement(By.xpath("(//div[@class='n6'])/descendant::span[3]/div")).click();
            Thread.sleep(10000);           
            driver.findElement(By.xpath("((//div[@class='aim'])/div/div/div/span/a)[last()]")).click();
            Thread.sleep(3000);            
            for(i=7;i<=20;)
            {
            List<WebElement> t=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            Thread.sleep(5000); 
            System.out.println("Count mails in Trash  "+ t.size());    
            Thread.sleep(10000);
            	for(i=1;i<=t.size();) 	
                {        	
        		driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[7]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[37]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[11]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[25]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[7]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[37]")).click();
            	Thread.sleep(2000);
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[11]")).click();            	
                }
            }
        	}
        if(x.equals("Primary"))
        {
        	//Count no.of mails in Primary
            driver.findElement(By.xpath("(//div[@class='aKz'])[1]")).click();
            Thread.sleep(2000);
            for(i=7;i<=20;i++)
            {
            List<WebElement> b=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            System.out.println(b.size()); 
            //Go to table inside
        	driver.findElement(By.xpath("(//div[@class='aKz'])[1]")).click();
        	@SuppressWarnings("resource")
			Scanner sc1=new Scanner(System.in);
        	System.out.println("Enter name ex:-Unread");
            String x1=sc1.nextLine();
            Thread.sleep(4000);
            //
            if(x1.equals("All"))
            {
            	for(i=1;i<=b.size();)
            {        	
        		d.click();
            	Thread.sleep(4000);            	
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
            	Thread.sleep(1000);
            	e.click();
            	Thread.sleep(4000);
            	f.click(); 
            	Thread.sleep(4000);
            	d.click();
            	Thread.sleep(4000);            	
            	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
            	Thread.sleep(1000);
            	e.click();
        	} 
            }            
            if(x1.equals("Read"))
            {
            	for(i=1;i<=b.size();)            
            {        	
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x1.equals("Unread"))
            {   
            	for(i=1;i<=b.size();)
            	{            	
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}  
            }
            if(x1.equals("Starred"))
            {
            	for(i=1;i<=b.size();)
            {        	
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x1.equals("Unstarred"))
            {      
            	for(i=1;i<=b.size();)
            	{            	
            		d.click();
            		Thread.sleep(4000);           	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
        }
        }
        if(x.equals("Social"))
        {
        	//Count no.of mails in Social
            driver.findElement(By.xpath("(//div[@class='aKz'])[2]")).click();
            Thread.sleep(2000);
            for(i=8;i<=20;i++)
            {
            List<WebElement> c=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            System.out.println(c.size()); 
            //Go to table inside
        	driver.findElement(By.xpath("(//div[@class='aKz'])[2]")).click();        	
        	@SuppressWarnings("resource")
			Scanner sc2=new Scanner(System.in);
        	System.out.println("Enter name ex:-Unread");
            String x2=sc2.nextLine();
            Thread.sleep(4000);
            if(x2.equals("All"))
            {        	
            	for(i=1;i<=c.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}    
            }
            if(x2.equals("Read"))
            {        	
            	for(i=1;i<=c.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x2.equals("Unread"))
            {      
            	for(i=1;i<=c.size();)
            	{
            		d.click();
            		Thread.sleep(4000);           	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}  
            }
            if(x2.equals("Starred"))
            {    
            	for(i=1;i<=c.size();)
            	{
            		d.click();
            		Thread.sleep(4000);           	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x2.equals("Unstarred"))
            {      
            	for(i=1;i<=c.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}    
            }
        } 
        }
        if(x.equals("Promotions"))
        {
        	 //Count no.of mails in Promotions
            driver.findElement(By.xpath("(//div[@class='aKz'])[3]")).click();
            Thread.sleep(2000);
            for(i=9;i<=20;i++)
            {
            List<WebElement> z=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            System.out.println(z.size()); 
            //Go to inside table
        	driver.findElement(By.xpath("(//div[@class='aKz'])[3]")).click();
        	@SuppressWarnings("resource")
			Scanner sc3=new Scanner(System.in);
        	System.out.println("Enter name ex:-Unread");
            String x3=sc3.nextLine();
            Thread.sleep(4000);
            if(x3.equals("All"))
            {    
            	for(i=1;i<=z.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}   
            }
            if(x3.equals("Read"))
            {   
            	for(i=1;i<=z.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x3.equals("Unread"))
            {
            	for(i=1;i<=z.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x3.equals("Starred"))
            {
            	for(i=1;i<=z.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x3.equals("Unstarred"))
            {
            	for(i=1;i<=z.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}
            }
        }
        }
        if(x.equals("Updates"))
        {
        	//Count no.of mails in Updates
            driver.findElement(By.xpath("(//div[@class='aKz'])[4]")).click();
            Thread.sleep(2000);
            for(i=10;i<=20;i++)
            {
            List<WebElement> y=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            System.out.println(y.size());
            //Go to inside table
        	driver.findElement(By.xpath("(//div[@class='aKz'])[4]")).click();
        	@SuppressWarnings("resource")
			Scanner sc4=new Scanner(System.in);
        	System.out.println("Enter name ex:-Unread");
            String x4=sc4.nextLine();
            Thread.sleep(4000);
            if(x4.equals("All"))
            {
            	for(i=1;i<=y.size();)
            	{
            		d.click();
            		Thread.sleep(4000);         	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}    
            }
            if(x4.equals("Read"))
            {
            	for(i=1;i<=y.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x4.equals("Unread"))
            {
            	for(i=1;i<=y.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}  
            }
            if(x4.equals("Starred"))
            {
            	for(i=1;i<=y.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x4.equals("Unstarred"))
            {
            	for(i=1;i<=y.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}  
            }
        }
        }
        if(x.equals("Forums"))
        {
        	//Count no.of mails in Forums
            driver.findElement(By.xpath("(//div[@class='aKz'])[5]")).click();
            Thread.sleep(2000);
            for(i=11;i<=20;i++)
            {
            List<WebElement> w=driver.findElements(By.xpath("(//table)["+i+"]/tbody/tr"));
            System.out.println(w.size()); 
            {
            //Go to inside table
        	driver.findElement(By.xpath("(//div[@class='aKz'])[5]")).click();
        	@SuppressWarnings("resource")
			Scanner sc5=new Scanner(System.in);
        	System.out.println("Enter name ex:-Unread");
            String x5=sc5.nextLine();
            Thread.sleep(4000);
            if(x5.equals("All"))
            {
            	for(i=1;i<=w.size();)
            	{
            		d.click();
            		Thread.sleep(4000);           	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[40]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}    
            }
            if(x5.equals("Read"))
            {
            	for(i=1;i<=w.size();)
            	{
            		d.click();
            		Thread.sleep(4000);           	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[44]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x5.equals("Unread"))
            {
            	for(i=1;i<=w.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[46]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}  
            }
            if(x5.equals("Starred"))
            {
            	for(i=1;i<=w.size();)
            	{
            		d.click();
            		Thread.sleep(4000);          	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[48]")).click();
                	Thread.sleep(1000);
                	e.click();
        	} 
            }
            if(x5.equals("Unstarred"))
            {
            	for(i=1;i<=w.size();)
            	{
            		d.click();
            		Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
                	Thread.sleep(4000);
                	f.click();
                	Thread.sleep(4000);
                	d.click();
                	Thread.sleep(4000);            	
                	driver.findElement(By.xpath("//div[@gh='mtb']/descendant::div[50]")).click();
                	Thread.sleep(1000);
                	e.click();
        	}    
            }
            }
        }
        }
        }       
        Thread.sleep(5000);
        //close
        driver.close();
	}	
}
